apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"guestbook","tier":"frontend"},"name":"guestbook-frontend","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"guestbook","tier":"frontend"}},"template":{"metadata":{"labels":{"app":"guestbook","tier":"frontend"}},"spec":{"containers":[{"env":[{"name":"GET_HOSTS_FROM","value":"dns"},{"name":"REDIS_MASTER_SERVICE_HOST","value":"redis-master"},{"name":"REDIS_MASTER_SERVICE_PORT","value":"6379"},{"name":"REDIS_SLAVE_SERVICE_HOST","value":"redis-slave"},{"name":"REDIS_SLAVE_SERVICE_PORT","value":"6379"}],"image":"guestbookacr2025br.azurecr.io/guestbook-frontend:v1","livenessProbe":{"httpGet":{"path":"/","port":3000},"initialDelaySeconds":15,"periodSeconds":10},"name":"guestbook-frontend","ports":[{"containerPort":3000}],"readinessProbe":{"httpGet":{"path":"/","port":3000},"initialDelaySeconds":10,"periodSeconds":5},"resources":{"limits":{"cpu":"250m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2025-10-06T00:22:56Z"
  generation: 3
  labels:
    app: guestbook
    tier: frontend
  name: guestbook-frontend
  namespace: default
  resourceVersion: "787878"
  uid: 246b7f91-cbf2-486b-a557-a1f68630ed42
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: REDIS_MASTER_SERVICE_HOST
          value: redis-master
        - name: REDIS_MASTER_SERVICE_PORT
          value: "6379"
        - name: REDIS_SLAVE_SERVICE_HOST
          value: redis-slave
        - name: REDIS_SLAVE_SERVICE_PORT
          value: "6379"
        image: guestbookacr2025br.azurecr.io/guestbook-frontend:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: guestbook-frontend
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2025-10-06T00:22:58Z"
    lastUpdateTime: "2025-10-06T00:22:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-06T00:22:56Z"
    lastUpdateTime: "2025-10-06T00:48:06Z"
    message: ReplicaSet "guestbook-frontend-78776f6f7d" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 3
  replicas: 4
  unavailableReplicas: 1
  updatedReplicas: 1
