name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: guestbookacr2025br
  AKS_RESOURCE_GROUP: yourResourceGroupName
  AKS_CLUSTER_NAME: yourAKSClusterName
  IMAGE_NAME: guestbook-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name $AZURE_CONTAINER_REGISTRY

    - name: Build and push Docker image
      run: |
        docker build -t $AZURE_CONTAINER_REGISTRY.azurecr.io/$IMAGE_NAME:v1 .
        docker push $AZURE_CONTAINER_REGISTRY.azurecr.io/$IMAGE_NAME:v1

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl apply -f guestbook-frontend.yaml
